function Hd = band_pass(Fs, N, Fc1, Fc2)
%BAND_PASS Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.1 and the Signal Processing Toolbox 7.3.
% Generated on: 09-Dec-2019 11:24:47

% Butterworth Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in Hz.
% Fs = 32000;  % Sampling Frequency
% 
% N   = 10;     % Order
% Fc1 = 3000;   % First Cutoff Frequency
% Fc2 = 10000;  % Second Cutoff Frequency

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.bandpass('N,F3dB1,F3dB2', N, Fc1, Fc2, Fs);
Hd = design(h, 'butter');

% [EOF]
